// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyAwNGIOIsEyhxpGghxvhOKitll2cOAsHGM',
      authDomain: "Channel Name-events.firebaseapp.com",
      projectId: "jewellery-app-8ff30",
      storageBucket: "jewellery-app-8ff30.appspot.com",
      messagingSenderId: "1062416029971",
      appId: "1:1062416029971:android:d829f4c4363c24306f62e6",
      );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxIvT5X3vsfiiV_uC4UCQ-oeVqwcxglLc',
    projectId: "Channel Name-events",
    storageBucket: "Channel Name-events.appspot.com",
    messagingSenderId: "307951879859",
    appId: "1:307951879859:ios:b4cf364172a86d5f5f12c6",
    iosBundleId: "com.Channel Name.com",
  );

}
